"""add appointment reminder_sent flag

Revision ID: 0a2a9fefc7ff
Revises: 7aa078b77ac3
Create Date: 2026-09-06 17:52:11.536654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2a9fefc7ff'
down_revision: Union[str, Sequence[str], None] = '7aa078b77ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: this table already has rows, and a
    # NOT NULL column with no default would fail against them.
    op.add_column(
        'appointments',
        sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent')
    # ### end Alembic commands ###
