"""add timestamps, constraints, and overlap exclusion

Revision ID: 1a9c5a9110fc
Revises: deed3f75acbf
Create Date: 2026-09-04 20:08:13.164644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9c5a9110fc'
down_revision: Union[str, Sequence[str], None] = 'deed3f75acbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('appointments_tenant_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_customer_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_service_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_customer_id_fkey', 'appointments', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('appointments_service_id_fkey', 'appointments', 'services', ['service_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('appointments_tenant_id_fkey', 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_appointments_status', 'appointments', "status IN ('booked', 'cancelled', 'completed')")
    op.add_column('customers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_customers_tenant_phone', 'customers', ['tenant_id', 'phone'])
    op.drop_constraint(op.f('customers_tenant_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key('customers_tenant_id_fkey', 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('services', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('services_tenant_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key('services_tenant_id_fkey', 'services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('working_hours', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('working_hours', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_working_hours_tenant_day', 'working_hours', ['tenant_id', 'day_of_week'])
    op.drop_constraint(op.f('working_hours_tenant_id_fkey'), 'working_hours', type_='foreignkey')
    op.create_foreign_key('working_hours_tenant_id_fkey', 'working_hours', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # Not autogenerated: Postgres exclusion constraint closing the
    # double-booking TOCTOU race. Requires btree_gist for the integer
    # equality operator class used alongside the native range-overlap (&&)
    # operator.
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    op.execute(
        """
        ALTER TABLE appointments
        ADD CONSTRAINT no_overlapping_bookings
        EXCLUDE USING gist (
            tenant_id WITH =,
            tsrange(start_time, end_time) WITH &&
        )
        WHERE (status = 'booked')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('working_hours_tenant_id_fkey', 'working_hours', type_='foreignkey')
    op.create_foreign_key(op.f('working_hours_tenant_id_fkey'), 'working_hours', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('uq_working_hours_tenant_day', 'working_hours', type_='unique')
    op.drop_column('working_hours', 'updated_at')
    op.drop_column('working_hours', 'created_at')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_constraint('services_tenant_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_tenant_id_fkey'), 'services', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_constraint('customers_tenant_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_tenant_id_fkey'), 'customers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('uq_customers_tenant_phone', 'customers', type_='unique')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')

    # Reverse of the hand-added exclusion constraint above (extension is
    # left installed — other objects may depend on it).
    op.execute('ALTER TABLE appointments DROP CONSTRAINT no_overlapping_bookings')

    op.drop_constraint('ck_appointments_status', 'appointments', type_='check')
    op.drop_constraint('appointments_customer_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_service_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_tenant_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_service_id_fkey'), 'appointments', 'services', ['service_id'], ['id'])
    op.create_foreign_key(op.f('appointments_customer_id_fkey'), 'appointments', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('appointments_tenant_id_fkey'), 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
