"""add whatsapp conversation selected appointment

Revision ID: 38a14ce1fcc3
Revises: 64185701f24f
Create Date: 2026-09-05 23:49:30.383139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a14ce1fcc3'
down_revision: Union[str, Sequence[str], None] = '64185701f24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_conversations', sa.Column('selected_appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'whatsapp_conversations', 'appointments', ['selected_appointment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_conversations', type_='foreignkey')
    op.drop_column('whatsapp_conversations', 'selected_appointment_id')
    # ### end Alembic commands ###
