"""add tenant whatsapp phone number id

Revision ID: 3a6ad2a9e0eb
Revises: 38a14ce1fcc3
Create Date: 2026-09-06 12:36:31.269621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6ad2a9e0eb'
down_revision: Union[str, Sequence[str], None] = '38a14ce1fcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['whatsapp_phone_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'whatsapp_phone_number_id')
    # ### end Alembic commands ###
