"""add time_blocks table

Revision ID: 4ca13b848de9
Revises: b77039a1eaae
Create Date: 2026-09-05 22:12:47.496173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca13b848de9'
down_revision: Union[str, Sequence[str], None] = 'b77039a1eaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_blocks_id'), 'time_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_time_blocks_start_time'), 'time_blocks', ['start_time'], unique=False)
    op.create_index(op.f('ix_time_blocks_tenant_id'), 'time_blocks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_blocks_tenant_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_start_time'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_id'), table_name='time_blocks')
    op.drop_table('time_blocks')
    # ### end Alembic commands ###
