"""add tenant contact info and conversation language/date/page

Revision ID: b77039a1eaae
Revises: ec00eff57e4c
Create Date: 2026-09-04 23:59:06.731051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77039a1eaae'
down_revision: Union[str, Sequence[str], None] = 'ec00eff57e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column(
        'whatsapp_conversations',
        sa.Column('language', sa.String(length=5), nullable=False, server_default='ar'),
    )
    op.add_column('whatsapp_conversations', sa.Column('selected_date', sa.Date(), nullable=True))
    op.add_column(
        'whatsapp_conversations',
        sa.Column('page', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_conversations', 'page')
    op.drop_column('whatsapp_conversations', 'selected_date')
    op.drop_column('whatsapp_conversations', 'language')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'phone')
    # ### end Alembic commands ###
