"""add whatsapp conversations table

Revision ID: ec00eff57e4c
Revises: 1a9c5a9110fc
Create Date: 2026-09-04 22:32:05.981251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec00eff57e4c'
down_revision: Union[str, Sequence[str], None] = '1a9c5a9110fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('selected_service_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone_number', name='uq_whatsapp_conversations_tenant_phone')
    )
    op.create_index(op.f('ix_whatsapp_conversations_id'), 'whatsapp_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_phone_number'), 'whatsapp_conversations', ['phone_number'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_tenant_id'), 'whatsapp_conversations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_conversations_tenant_id'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_phone_number'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_id'), table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    # ### end Alembic commands ###
